name: Playwright Tests

on:
  #push:
  #  branches: 
  #      - main
  #      - master
  #      - develop
  #pull_request:
  #  branches: 
  #      - main
  #      - master
  #      - develop
  schedule:
    - cron: "0 13 * * *" # Runs at 13:00 UTC (8 AM EST)
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # Virtual Machine (macos-latest, windows-latest, ubuntu-latest etc.)
    permissions:
      contents: write

    # Set up NodeJS version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Chromium Browser
      - name: Install Playwright Chrome
        run: npx playwright install --with-deps chromium

      # configuring environment variables Example:
      - name: Configure environment variables from secrets
        run: |
          echo "PRACTICE_USERNAME=${{ secrets.PRACTICE_USERNAME }}" >> .env
          echo "PRACTICE_PASSWORD=${{ secrets.PRACTICE_PASSWORD }}" >> .env
          

      # Running tests with Playwright
      - name: Run Playwright tests
        run: npm run tests:headless

      # Generating Playwright test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30
      
      # Generating Playwright HTML report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
